let Data = {
    userInfo:{
    	//抽奖次数
    	luckDrawNumber:5
    },
    //标题
    title:'标题标题标题',
    //banner图片地址
    banner:'http://frontendsvn.360che.com/icon-project/wap/m/product-library/M/images/banner.png',
    //广告位
    adData:{
	    name:'主标题主标题',
	    subTitle:'副标题说明说明说明',
	    src:'http://designsvn.360che.com/design_web/LJL/10.18_BusinessPromotion/assets/%E5%BC%BA%E8%B0%83%E6%B4%BB%E5%8A%A8.png'
    },
	//nav导航
	nav:[
		{
		  name:'厂商介绍',
		  icon:'http://designsvn.360che.com/design_web/LJL/10.18_BusinessPromotion/assets/%E8%BD%A6%E5%9E%8B%E8%AE%BA%E5%9D%9B.svg',
		},
		{
		  name:'优惠买车',
		  icon:'',
		},
		{
		  name:'整点秒杀',
		  icon:'',
		},
		{
		  name:'一口价优惠',
		  icon:'https://s.kcimg.cn/wap/images/detail/productApp/more.png',
		  more:true,
		}
	],
	//厂商推荐
	recommendData:{
		title:'厂商推荐',
		subTitle:{
		  name:'推广标题厂商推广标题',
		  src:'http://placeholder.qiniudn.com/688x144'
		},
		list:[
		  'http://placeholder.qiniudn.com/224x80',
		  'http://placeholder.qiniudn.com/224x80',
		  'http://placeholder.qiniudn.com/224x80'
		],
	},
	//优惠买车
	discountData:{
		title:'优惠买车',
		list:[
				{
					tag:'标签表',
					src:'http://placeholder.qiniudn.com/336x224',
					srcText:'图上文字图上文字',
					title:'车型标题车型标题车型...',
					peice:'29.2',
					guidingPrice:'33.3',
					buttons:[
				  		{
				    		text:'立即抢购'
				  		}
					]
				},
				{
					tag:'标签表',
					src:'http://placeholder.qiniudn.com/336x224',
					srcText:'图上文字图上文字',
					title:'车型标题车型标题车型...',
					peice:'29.2',
					guidingPrice:'33.3',
					buttons:[
						{
							text:'立即抢购'
						}
					]
				},
				{
					tag:'标签表',
					src:'http://placeholder.qiniudn.com/336x224',
					srcText:'图上文字图上文字',
					title:'车型标题车型标题车型...',
					peice:'29.2',
					guidingPrice:'33.3',
					buttons:[
						{
							text:'立减2000'
						},
						{
							text:'立即抢购'
						}
					]
				},
				{
					tag:'标签表',
					src:'http://placeholder.qiniudn.com/336x224',
					srcText:'图上文字图上文字',
					title:'车型标题车型标题车型...',
					peice:'29.2',
					guidingPrice:'33.3',
					buttons:[
						{
							text:'立减2000'
						},
						{
							text:'立即抢购'
						}
					]
				}
		],
	},
	//整点秒杀
	seckillData:{
		title:'整点秒杀',
		navList:[
			{
				oclock:'12:00',
				status:'已开抢'
			},
			{
				oclock:'15:00',
				status:'已开抢'
			},
			{
				oclock:'18:00',
				status:'抢购中'
			},
			{
				oclock:'21:00',
				status:'即将抢购'
			},
			{
				oclock:'24:00',
				status:'即将抢购'
			},
		],
		goodsList:[
			{
				src:'http://placeholder.qiniudn.com/270x180',
				name:'一汽解放 J6P 540马力',
				price:'29.2',
				guidingPrice:'33.3',
				surplus:5,
				Total:20
			},
			{
				src:'http://placeholder.qiniudn.com/270x180',
				name:'一汽解放 J6P 540马力',
				price:'29.2',
				guidingPrice:'33.3',
				surplus:0,
			},
			{
				src:'http://placeholder.qiniudn.com/270x180',
				name:'一汽解放 J6P 540马力',
				price:'29.2',
				guidingPrice:'33.3',
				surplus:17,
				Total:18
			}
		]
	},
	// 底部导航栏
	footerData:[
		{
			name:'首页',
			src:'http://placeholder.qiniudn.com/48x48',
			select:true
		},
		{
			name:'其他',
			src:'http://placeholder.qiniudn.com/48x48'
		},
		{
			name:'其他',
			src:'http://placeholder.qiniudn.com/48x48'
		},
		{
			name:'其他',
			src:'http://placeholder.qiniudn.com/48x48'
		},
		{
			name:'其他',
			src:'http://placeholder.qiniudn.com/48x48'
		},
	]
}